#!/usr/bin/env bash

function get_value(){
  local hexinput=`echo $1 | tr -d '#' | tr '[:lower:]' '[:upper:]'` #uppercaseing

  local a=`echo $hexinput | cut -c-2`
  local b=`echo $hexinput | cut -c3-4`
  local c=`echo $hexinput | cut -c5-6`

  local r=`echo "ibase=16; $a" | bc`
  local g=`echo "ibase=16; $b" | bc`
  local b=`echo "ibase=16; $c" | bc`

  echo "$((${r} + ${g} + ${b}))"
}

function main(){
  local colorList=''
  local colorValue=0

  while read curColor; do
    colorValue=$(get_value "${curColor}")
    colorList+="${colorValue};${curColor}\n"
  done

  colorList=$(echo -e "${colorList}" | sort -n -t ';')

  echo "${colorList}" | while read colorLine; do
    echo -n "${colorLine}" | awk -F ';' '{print $2}'
  done
}

main