#!/usr/bin/env bash

scriptDir=$(dirname `realpath -P "$0"`)
image="${1:-$IMAGE}"

function merge_colors(){
  local greyColors=('#181818' '#282828' '#383838' '#585858' '#b8b8b8' '#d8d8d8' '#e8e8e8' '#f8f8f8')
  echo -e "${greyColors[@]} ${@}" | tr ' ' '\n'
}

function main(){
  local fName="${1}"

  if [[ -f "${fName}" ]]; then
    local themeDir="${HOME}/.wp-themes/$(md5sum ${fName} | awk -F ' ' '{print $1}')"

    if [[ -d "${themeDir}" ]] && [[ "${FORCE_UPDATE}" == "" ]]; then
      echo -e "[INFO] Theme for \"${fName}\" already generated. Saved as \"${themeDir}\"\n"
      return
    fi

    echo -e "[INFO] Generating theme for \"${fName}\". Saving as \"${themeDir}\"\n"

    mkdir -p "${themeDir}"

    local midColors=$(echo "${fName}" | "${scriptDir}/img2col" | "${scriptDir}/col2mid")
    local fullColors=$(merge_colors ${midColors})
    echo -e "${fullColors}" > "${themeDir}/palette.list"
    #echo "${fName}" | "${scriptDir}/img2col" | "${scriptDir}/col2pal" "${themeDir}/palette.list"
    #echo -e "$(xres2col ~/downloads/base16-default.dark.xresources)" > "${themeDir}/palette.list"
    cat "${themeDir}/palette.list" | "${scriptDir}/col2prv" "${themeDir}/preview.png"
    cat "${themeDir}/palette.list" | "${scriptDir}/col2thm" "${themeDir}"
    echo "${fName}" > "${themeDir}/wallpaper.txt"
  else
    echo -e "[INFO] File not found: \"${fName}\""
  fi
}

if [[ "${image}" != "" ]]; then
  main "${image}"
else
  while read fName; do
    main "${fName}"
  done < "${image:-/dev/stdin}"
fi

